### ISSUE TITLE
[BUILD] Making a build for this plugin.

### ISSUE THREAD

**Issue by darkwolfie37** [cooffeeRequired/skGoat#1]
This Issue will be updated with said plugin.

**Comment by darkwolfie37** [comment]
BUILD V1.0 https://drive.google.com/file/d/1zkLEBttU-phe80__k3M7gsaKsRQVPN_p/view?usp=share_link

**Comment by darkwolfie37** [comment]
Reopened to people can see

**Comment by cooffeeRequired** [comment]
Hello there. now you can build. @darkwolfie37

**Comment by darkwolfie37** [comment]
> Hello there. now you can build. @darkwolfie37

I need to have contributor perms or someway of making releases.
